language: csharp
solution: DotNetStandardCalculator.sln

matrix:
  include:
    - dotnet: 1.1.5
      mono: none
    #- mono: latest

script:
  - cd ./DotNetStandardCalculatorTests
  - dotnet restore
  - dotnet build
  - dotnet test
