language: csharp
solution: DotNetStandardCalculator.sln

dotnet: 1.1.5
mono: none

install:
  - dotnet restore

stages:
  - build
  - test
  - name: package
    #if: branch = master

jobs:
  include:
    - stage: build
      script:
        - dotnet build
    - stage: test
      script:
        - dotnet test ./DotNetStandardCalculatorTests/DotNetStandardCalculatorTests.csproj
    - stage: deploy
      script:
        - dotnet pack -c Release
        - echo "To be implemented"