language: csharp
solution: DotNetStandardCalculator.sln

dotnet: 1.1.5
mono: none

install:
  - dotnet restore

stages:
  - test
  - name: package
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - dotnet build
        - dotnet test
    - stage: deploy
      script:
        - dotnet build
        - dotnet pack -c Release
        - echo "To be implemented"
